import type { RepairActionDefinition, RepairActionId } from "./contracts";

export const REPAIR_ACTIONS: RepairActionDefinition[] = [
  {
    id: "quick-repair",
    title: "智能安全修复",
    description: "清理 DNS 缓存，关闭指向无监听端口的系统代理，并移除已断开的 TUN 默认路由。",
    risk: "low",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "网页突然变慢、代理切换后断流、关掉软件仍受影响",
    steps: ["创建完整网络快照", "刷新 DNS 缓存", "验证本地代理端口", "清理断开的隧道路由"],
  },
  {
    id: "flush-dns",
    title: "刷新 DNS 缓存",
    description: "清除 Windows DNS 客户端缓存，不更改 DNS 服务器。",
    risk: "low",
    requiresAdmin: false,
    restartRequired: false,
    recommendedFor: "部分网站打不开、域名解析到旧地址",
    steps: ["执行 Clear-DnsClientCache", "执行 ipconfig /flushdns"],
  },
  {
    id: "renew-dhcp",
    title: "重新获取 IP",
    description: "释放并重新申请 DHCP 地址，操作期间会短暂断网。",
    risk: "medium",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "连接路由器后无网、网关或 IP 地址异常",
    steps: ["创建网络快照", "释放 DHCP 地址", "重新申请地址", "刷新 DNS"],
  },
  {
    id: "dns-auto",
    title: "DNS 恢复自动",
    description: "仅将当前已连接的物理网卡恢复为 DHCP 自动 DNS，跳过代理和虚拟网卡。",
    risk: "medium",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "关掉代理后很慢、DNS 被旧软件固定为公共地址",
    steps: ["创建网络快照", "筛选已连接物理网卡", "恢复自动 DNS", "刷新缓存"],
  },
  {
    id: "disable-dead-proxy",
    title: "关闭失效系统代理",
    description: "只有系统代理指向本机且端口无人监听时才会关闭，不会退出代理软件。",
    risk: "low",
    requiresAdmin: false,
    restartRequired: false,
    recommendedFor: "代理软件已关但浏览器仍一直转圈",
    steps: ["创建网络快照", "解析系统代理端口", "检查端口监听", "仅在失效时关闭代理"],
  },
  {
    id: "reset-winhttp-proxy",
    title: "重置 WinHTTP 代理",
    description: "清除后台服务使用的 WinHTTP 代理，不影响浏览器的用户代理设置。",
    risk: "medium",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "命令行、更新服务或 Codex 超时，但浏览器正常",
    steps: ["创建网络快照", "执行 netsh winhttp reset proxy"],
  },
  {
    id: "sync-winhttp-proxy",
    title: "同步系统代理到 WinHTTP",
    description: "把当前 Windows 用户代理同步给后台程序，适合浏览器可用但命令行直连失败。",
    risk: "medium",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "浏览器能翻墙，后台程序或部分客户端一直超时",
    steps: ["创建网络快照", "从 Internet 设置导入 WinHTTP 代理"],
  },
  {
    id: "normalize-proxy-bypass",
    title: "补全局域网直连规则",
    description: "保留现有规则并加入 localhost 与常见局域网网段，减少代理回环和访问路由器失败。",
    risk: "low",
    requiresAdmin: false,
    restartRequired: false,
    recommendedFor: "开代理后 NAS、路由器或本地服务打不开",
    steps: ["创建网络快照", "保留当前例外", "追加本机与局域网直连规则"],
  },
  {
    id: "remove-orphan-tun-routes",
    title: "清理断开的 TUN 路由",
    description: "只移除状态非 Up 的隧道/代理网卡上的默认路由，不动正在使用的 TUN。",
    risk: "medium",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "关掉 Clash/代理后仍慢，路由表还指向旧 TUN",
    steps: ["创建网络快照", "识别隧道网卡", "确认网卡已断开", "删除其默认路由"],
  },
  {
    id: "restart-active-adapters",
    title: "重启当前网卡",
    description: "重启已连接的物理网卡，网络会中断约 5 到 15 秒。",
    risk: "medium",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "网卡显示已连接但吞吐异常或长期卡顿",
    steps: ["创建网络快照", "筛选已连接物理网卡", "禁用并重新启用"],
  },
  {
    id: "reset-winsock",
    title: "重置 Winsock",
    description: "重建网络程序调用链，适合 LSP/代理软件卸载残留；完成后建议重启。",
    risk: "medium",
    requiresAdmin: true,
    restartRequired: true,
    recommendedFor: "多个程序同时连不上、卸载 VPN 后网络异常",
    steps: ["创建网络快照", "执行 netsh winsock reset"],
  },
  {
    id: "reset-tcpip",
    title: "重置 TCP/IP",
    description: "重置 Windows IPv4/IPv6 网络栈配置，可能清除自定义接口设置。",
    risk: "high",
    requiresAdmin: true,
    restartRequired: true,
    recommendedFor: "常规修复无效、IP 栈配置损坏",
    steps: ["创建网络快照", "重置 IPv4", "重置 IPv6", "刷新 DNS"],
  },
  {
    id: "reset-firewall",
    title: "重置防火墙规则",
    description: "导出当前防火墙策略后恢复默认。会移除第三方和自定义入站/出站规则。",
    risk: "high",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "确认是防火墙规则导致连接异常时",
    steps: ["创建网络快照", "导出防火墙策略", "恢复 Windows 防火墙默认规则"],
  },
  {
    id: "reset-hosts",
    title: "重置 Hosts 文件",
    description: "备份后将 Hosts 恢复为仅包含 localhost 的安全默认内容。",
    risk: "high",
    requiresAdmin: true,
    restartRequired: false,
    recommendedFor: "Hosts 被软件篡改、指定网站总是跳到错误地址",
    steps: ["创建网络快照", "备份 Hosts", "写入默认内容", "刷新 DNS"],
  },
  {
    id: "full-network-reset",
    title: "彻底重装网络组件",
    description: "执行 netcfg -d，移除并重新安装所有网卡组件，包括虚拟网卡。必须重启。",
    risk: "high",
    requiresAdmin: true,
    restartRequired: true,
    recommendedFor: "其他方案全部无效的最后手段",
    steps: ["创建网络快照", "导出防火墙策略", "执行 netcfg -d", "等待重启后 Windows 重装网卡"],
  },
];

export const getRepairAction = (id: RepairActionId): RepairActionDefinition => {
  const action = REPAIR_ACTIONS.find((candidate) => candidate.id === id);
  if (!action) throw new Error(`未知修复动作：${id}`);
  return action;
};
